export const topUserList = [
  {
    name: 'Reja Jamil',
    level: 'Super',
    rating: 3,
    sold: 33,
    avatar: require('@assets/icons/user_1.png'),
  },
  {
    name: 'Reja Jamil',
    level: 'Mall',
    rating: 5,
    sold: 54,
    avatar: require('@assets/icons/user_5.png'),
  },
  {
    name: 'Reja Jamil',
    level: 'Silver',
    rating: 1,
    sold: 24,
    avatar: require('@assets/icons/user_3.png'),
  },
  {
    name: 'Reja Jamil',
    level: 'Gold',
    rating: 1,
    sold: 11,
    avatar: require('@assets/icons/user_4.png'),
  },
  {
    name: 'Reja Jamil',
    level: 'Platinum',
    rating: 4,
    sold: 240,
    avatar: require('@assets/icons/user_2.png'),
  },
]
export const userList = [
  {
    name: 'John McCall',
    avatar: require('@assets/icons/user_1.png'),
  },
  {
    name: 'Reja Jamil',
    avatar: require('@assets/icons/user_5.png'),
  },
  {
    name: 'Jane Doe',
    avatar: require('@assets/icons/user_3.png'),
  },
  {
    name: 'Reja Jamil',
    avatar: require('@assets/icons/user_4.png'),
  },
  {
    name: 'Charles',
    avatar: require('@assets/icons/user_2.png'),
  },
  {
    name: 'Marry Jane',
    avatar: require('@assets/icons/user_6.png'),
  },
]
export const productsList = [
  {
    name: 'Men Returnable Jacket Bb Dc 2in1 Anti Air Parachute Fleece SIZE M L XL XXL',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.100.000',
    rating: 3,
    likes: 30,
    sold: 33,
    src: 'https://rejacopyright.github.io/static/media/1.74ab4f78.jpg',
  },
  {
    name: 'Trucker Men Jacket SIZE M-XXL COD',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 850.000',
    rating: 5,
    likes: 30,
    sold: 54,
    src: 'https://rejacopyright.github.io/static/media/2.2d856cf1.jpg',
  },
  {
    name: 'Mens Premium Screen Printed Denim Jean Jacket',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.250.000',
    rating: 1,
    likes: 30,
    sold: 24,
    src: 'https://rejacopyright.github.io/static/media/3.eea0aa8b.jpg',
  },
  {
    name: 'Elmour Windproof Torque Series Softshell Motorcycle Jacket is Water and Wind Resistant',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 750.000',
    rating: 1,
    likes: 230,
    sold: 11,
    src: 'https://rejacopyright.github.io/static/media/5.b2343a7b.jpg',
  },
  {
    name: 'Harrington Jacket Windproof Waterproof Rexio Series',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.450.000',
    rating: 4,
    likes: 823,
    sold: 240,
    src: 'https://rejacopyright.github.io/static/media/4.61cb230d.jpg',
  },
  {
    name: 'Daily Outdoor Jacket Hike Series Black Grey',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 650.000',
    rating: 2,
    likes: 765,
    sold: 254,
    src: 'https://rejacopyright.github.io/static/media/8.f1b7dcac.jpg',
  },
  {
    name: 'Triple F Outdoor Waterproof jacket/men parachute jacket/motorcycle jacket/mountain jacket/hiking jacket',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 650.000',
    rating: 3,
    likes: 334,
    sold: 115,
    src: 'https://rejacopyright.github.io/static/media/9.630e054e.jpg',
  },
  {
    name: 'Men Motorcycle Jacket, Premium Bonding Material, Windproof Jacket, Suitable for Touring or Original Restart Style',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.650.000',
    rating: 4,
    likes: 221,
    sold: 44,
    src: 'https://rejacopyright.github.io/static/media/14.daf0dc23.jpg',
  },
  {
    name: 'Premium Outdoor Indoor Winter Waterproof Semi Jacket',
    description: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.650.000',
    rating: 5,
    likes: 169,
    sold: 442,
    src: 'https://rejacopyright.github.io/static/media/15.e22039de.jpg',
  },
]
