export const topUserList = [
  {
    name: 'Reja Jamil',
    level: 'Super',
    rating: 3,
    sold: 33,
    avatar: require('@assets/icons/user_1.png'),
  },
  {
    name: 'Reja Jamil',
    level: 'Mall',
    rating: 5,
    sold: 54,
    avatar: require('@assets/icons/user_5.png'),
  },
  {
    name: 'Reja Jamil',
    level: 'Silver',
    rating: 1,
    sold: 24,
    avatar: require('@assets/icons/user_3.png'),
  },
  {
    name: 'Reja Jamil',
    level: 'Gold',
    rating: 1,
    sold: 11,
    avatar: require('@assets/icons/user_4.png'),
  },
  {
    name: 'Reja Jamil',
    level: 'Platinum',
    rating: 4,
    sold: 240,
    avatar: require('@assets/icons/user_2.png'),
  },
]
export const productsList = [
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.100.000',
    rating: 3,
    likes: 30,
    sold: 33,
    src: 'https://rejacopyright.github.io/static/media/1.74ab4f78.jpg',
  },
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 850.000',
    rating: 5,
    likes: 30,
    sold: 54,
    src: 'https://rejacopyright.github.io/static/media/2.2d856cf1.jpg',
  },
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.250.000',
    rating: 1,
    likes: 30,
    sold: 24,
    src: 'https://rejacopyright.github.io/static/media/3.eea0aa8b.jpg',
  },
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 750.000',
    rating: 1,
    likes: 230,
    sold: 11,
    src: 'https://rejacopyright.github.io/static/media/5.b2343a7b.jpg',
  },
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.450.000',
    rating: 4,
    likes: 823,
    sold: 240,
    src: 'https://rejacopyright.github.io/static/media/4.61cb230d.jpg',
  },
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 650.000',
    rating: 2,
    likes: 765,
    sold: 254,
    src: 'https://rejacopyright.github.io/static/media/8.f1b7dcac.jpg',
  },
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 650.000',
    rating: 3,
    likes: 334,
    sold: 115,
    src: 'https://rejacopyright.github.io/static/media/9.630e054e.jpg',
  },
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.650.000',
    rating: 4,
    likes: 221,
    sold: 44,
    src: 'https://rejacopyright.github.io/static/media/14.daf0dc23.jpg',
  },
  {
    name: 'Lorem ipsum is placeholder',
    descripition: 'Lorem ipsum is placeholder text commonly used in the graphic',
    price: 'Rp. 1.650.000',
    rating: 5,
    likes: 169,
    sold: 442,
    src: 'https://rejacopyright.github.io/static/media/15.e22039de.jpg',
  },
]
